org: lucasbbs
service: serverless-authV1

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.run
    events:
      - http:
          path: /status
          method: get
          cors: true
      - http:
          path: /login
          method: post
          cors: true
      - http:
          path: /register
          method: post
          cors: true
